### ISSUE TITLE
Is there something missing from the install description?

### ISSUE THREAD

**Issue by Bali10050** [ashish-kus/MiniSthetic_Firefox#1]
The tabs don't seem to be in their own place, did I miss something from the install, or is there a different problem?
![Screenshot_20241103_001109](https://github.com/user-attachments/assets/299cfb7f-7a78-45d1-a5cd-7f86d3dcbcaf)

`browser.proton.enabled` = `false`
`browser.tabs.drawInTitlebar` = `false`
`toolkit.legacyUserProfileCustomizations.stylesheets` = `false`
Everything is in the `chrome` folder

Firefox Version 132.0 and 134.0a1
Archlinux with KDE Wayland

**Comment by ashish-kus** [comment]
Sorry for the extra steps, but this will enable vertical tabs in Firefox.
     sidebar.revamp and set it to true.
     sidebar.verticalTabs and also set it to true.

**Comment by Bali10050** [comment]
It still doesn't look right, but it's different
![Screenshot_20241103_005314](https://github.com/user-attachments/assets/6ba71cc1-b1d3-4d1b-bdf2-6508a68e57f3)

**Comment by ashish-kus** [comment]
Okay, this is strange,  can you once try the latest update I pushed?

**Comment by Bali10050** [comment]
Still the same, have you tried it on a clean profile?
![Screenshot_20241103_021516](https://github.com/user-attachments/assets/dbb1203a-1131-41c4-8ad4-5850372f84ae)

**Comment by ashish-kus** [comment]
Hey, sorry about the confusion! My mind was a bit exhausted last night. There’s an update on the setup instructions:

Updated Step 2:

The settings browser.tabs.drawInTitlebar and browser.proton.enabled are unnecessary. Those were specific to another theme I was testing.

I’ve updated the README to reflect the correct instructions. If you follow the steps there, everything should work fine now. Thanks for your patience!

**Comment by Bali10050** [comment]
I might be missing something, but it seems that it just became a mix between the two states
![Screenshot_20241103_091518](https://github.com/user-attachments/assets/2a61f27a-f0fd-4bce-b9e3-5d427d4db4e4)

**Comment by ashish-kus** [comment]
First check if you have enabled virticleTabs from `about:config`, search sidebar.verticalTab. This should be true.
![image](https://github.com/user-attachments/assets/08031410-dfa5-4ce5-8357-b5eb875a46ef)

If this doesn't fix  check In ```about:config```  try changing ```browser.proton.enabled```  &  ```browser.tabs.drawInTitlebar``` to Boolean.
If this also doesn't work > Go to `about:config`, type `modified` in the search bar, right-click each modified setting, and select **Reset**.

**Comment by ashish-kus** [comment]
The issue was because I was not using the latest version, now everything is fixed according to the Latest update.
